// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Codefresh.Outputs
{

    [OutputType]
    public sealed class GetUsersUserResult
    {
        public readonly string Email;
        public readonly ImmutableArray<Outputs.GetUsersUserLoginResult> Logins;
        public readonly ImmutableArray<Outputs.GetUsersUserPersonalResult> Personals;
        public readonly ImmutableArray<string> Roles;
        public readonly ImmutableArray<Outputs.GetUsersUserShortProfileResult> ShortProfiles;
        public readonly string Status;
        public readonly string UserId;
        public readonly string UserName;

        [OutputConstructor]
        private GetUsersUserResult(
            string email,

            ImmutableArray<Outputs.GetUsersUserLoginResult> logins,

            ImmutableArray<Outputs.GetUsersUserPersonalResult> personals,

            ImmutableArray<string> roles,

            ImmutableArray<Outputs.GetUsersUserShortProfileResult> shortProfiles,

            string status,

            string userId,

            string userName)
        {
            Email = email;
            Logins = logins;
            Personals = personals;
            Roles = roles;
            ShortProfiles = shortProfiles;
            Status = status;
            UserId = userId;
            UserName = userName;
        }
    }
}
