// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Codefresh.Outputs
{

    [OutputType]
    public sealed class GetUserPersonalResult
    {
        public readonly string? CompanyName;
        public readonly string? Country;
        public readonly string? FirstName;
        public readonly string? LastName;
        public readonly string? PhoneNumber;

        [OutputConstructor]
        private GetUserPersonalResult(
            string? companyName,

            string? country,

            string? firstName,

            string? lastName,

            string? phoneNumber)
        {
            CompanyName = companyName;
            Country = country;
            FirstName = firstName;
            LastName = lastName;
            PhoneNumber = phoneNumber;
        }
    }
}
