// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Codefresh.Outputs
{

    [OutputType]
    public sealed class GetUsersUserLoginResult
    {
        public readonly ImmutableArray<Outputs.GetUsersUserLoginCredentialResult> Credentials;
        public readonly ImmutableArray<Outputs.GetUsersUserLoginIdpResult> Idps;

        [OutputConstructor]
        private GetUsersUserLoginResult(
            ImmutableArray<Outputs.GetUsersUserLoginCredentialResult> credentials,

            ImmutableArray<Outputs.GetUsersUserLoginIdpResult> idps)
        {
            Credentials = credentials;
            Idps = idps;
        }
    }
}
