// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Codefresh.Outputs
{

    [OutputType]
    public sealed class StepTypesVersion
    {
        /// <summary>
        /// YAML String containing a valid definition of a typed plugin
        /// </summary>
        public readonly string StepTypesYaml;
        /// <summary>
        /// String representing the semVer for the step
        /// </summary>
        public readonly string VersionNumber;

        [OutputConstructor]
        private StepTypesVersion(
            string stepTypesYaml,

            string versionNumber)
        {
            StepTypesYaml = stepTypesYaml;
            VersionNumber = versionNumber;
        }
    }
}
