# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .account import *
from .account_admins import *
from .api_key import *
from .context import *
from .get_account import *
from .get_context import *
from .get_current_account import *
from .get_idps import *
from .get_registry import *
from .get_step_types import *
from .get_team import *
from .get_user import *
from .get_users import *
from .idp_accounts import *
from .permission import *
from .pipeline import *
from .pipeline_cron_trigger import *
from .project import *
from .provider import *
from .registry import *
from .step_types import *
from .team import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_codefresh.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_codefresh.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "codefresh",
  "mod": "index/account",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/account:Account": "Account"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/accountAdmins",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/accountAdmins:AccountAdmins": "AccountAdmins"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/apiKey",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/apiKey:ApiKey": "ApiKey"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/context",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/context:Context": "Context"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/idpAccounts",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/idpAccounts:IdpAccounts": "IdpAccounts"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/permission",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/permission:Permission": "Permission"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/pipeline",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/pipeline:Pipeline": "Pipeline"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/pipelineCronTrigger",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/pipelineCronTrigger:PipelineCronTrigger": "PipelineCronTrigger"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/project",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/project:Project": "Project"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/registry",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/registry:Registry": "Registry"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/stepTypes",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/stepTypes:StepTypes": "StepTypes"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/team",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/team:Team": "Team"
  }
 },
 {
  "pkg": "codefresh",
  "mod": "index/user",
  "fqn": "pulumi_codefresh",
  "classes": {
   "codefresh:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "codefresh",
  "token": "pulumi:providers:codefresh",
  "fqn": "pulumi_codefresh",
  "class": "Provider"
 }
]
"""
)
