# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'GetStepTypesResult',
    'AwaitableGetStepTypesResult',
    'get_step_types',
    'get_step_types_output',
]

@pulumi.output_type
class GetStepTypesResult:
    """
    A collection of values returned by getStepTypes.
    """
    def __init__(__self__, id=None, name=None, versions=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if versions and not isinstance(versions, list):
            raise TypeError("Expected argument 'versions' to be a list")
        pulumi.set(__self__, "versions", versions)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def versions(self) -> Sequence['outputs.GetStepTypesVersionResult']:
        """
        A Set of `version` blocks as documented below.
        """
        return pulumi.get(self, "versions")


class AwaitableGetStepTypesResult(GetStepTypesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetStepTypesResult(
            id=self.id,
            name=self.name,
            versions=self.versions)


def get_step_types(name: Optional[str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetStepTypesResult:
    """
    ## # Data Source: StepTypes

    This data source allows to retrieve the published versions of a step-types


    :param str name: Name of the step-types to be retrieved
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('codefresh:index/getStepTypes:getStepTypes', __args__, opts=opts, typ=GetStepTypesResult).value

    return AwaitableGetStepTypesResult(
        id=__ret__.id,
        name=__ret__.name,
        versions=__ret__.versions)


@_utilities.lift_output_func(get_step_types)
def get_step_types_output(name: Optional[pulumi.Input[str]] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetStepTypesResult]:
    """
    ## # Data Source: StepTypes

    This data source allows to retrieve the published versions of a step-types


    :param str name: Name of the step-types to be retrieved
    """
    ...
