# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['PipelineCronTriggerArgs', 'PipelineCronTrigger']

@pulumi.input_type
class PipelineCronTriggerArgs:
    def __init__(__self__, *,
                 expression: pulumi.Input[str],
                 message: pulumi.Input[str],
                 pipeline_id: pulumi.Input[str]):
        """
        The set of arguments for constructing a PipelineCronTrigger resource.
        :param pulumi.Input[str] expression: The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        :param pulumi.Input[str] message: The message which will be passed to the pipeline upon each trigger.
        :param pulumi.Input[str] pipeline_id: The pipeline to which this trigger belongs.
        """
        pulumi.set(__self__, "expression", expression)
        pulumi.set(__self__, "message", message)
        pulumi.set(__self__, "pipeline_id", pipeline_id)

    @property
    @pulumi.getter
    def expression(self) -> pulumi.Input[str]:
        """
        The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        """
        return pulumi.get(self, "expression")

    @expression.setter
    def expression(self, value: pulumi.Input[str]):
        pulumi.set(self, "expression", value)

    @property
    @pulumi.getter
    def message(self) -> pulumi.Input[str]:
        """
        The message which will be passed to the pipeline upon each trigger.
        """
        return pulumi.get(self, "message")

    @message.setter
    def message(self, value: pulumi.Input[str]):
        pulumi.set(self, "message", value)

    @property
    @pulumi.getter(name="pipelineId")
    def pipeline_id(self) -> pulumi.Input[str]:
        """
        The pipeline to which this trigger belongs.
        """
        return pulumi.get(self, "pipeline_id")

    @pipeline_id.setter
    def pipeline_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "pipeline_id", value)


@pulumi.input_type
class _PipelineCronTriggerState:
    def __init__(__self__, *,
                 expression: Optional[pulumi.Input[str]] = None,
                 message: Optional[pulumi.Input[str]] = None,
                 pipeline_id: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering PipelineCronTrigger resources.
        :param pulumi.Input[str] expression: The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        :param pulumi.Input[str] message: The message which will be passed to the pipeline upon each trigger.
        :param pulumi.Input[str] pipeline_id: The pipeline to which this trigger belongs.
        """
        if expression is not None:
            pulumi.set(__self__, "expression", expression)
        if message is not None:
            pulumi.set(__self__, "message", message)
        if pipeline_id is not None:
            pulumi.set(__self__, "pipeline_id", pipeline_id)

    @property
    @pulumi.getter
    def expression(self) -> Optional[pulumi.Input[str]]:
        """
        The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        """
        return pulumi.get(self, "expression")

    @expression.setter
    def expression(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "expression", value)

    @property
    @pulumi.getter
    def message(self) -> Optional[pulumi.Input[str]]:
        """
        The message which will be passed to the pipeline upon each trigger.
        """
        return pulumi.get(self, "message")

    @message.setter
    def message(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "message", value)

    @property
    @pulumi.getter(name="pipelineId")
    def pipeline_id(self) -> Optional[pulumi.Input[str]]:
        """
        The pipeline to which this trigger belongs.
        """
        return pulumi.get(self, "pipeline_id")

    @pipeline_id.setter
    def pipeline_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "pipeline_id", value)


class PipelineCronTrigger(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expression: Optional[pulumi.Input[str]] = None,
                 message: Optional[pulumi.Input[str]] = None,
                 pipeline_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        ## # Pipeline Cron Trigger resource

        Pipeline Cron Trigger is used to create cron-based triggers for pipeilnes.
        See the [documentation](https://codefresh.io/docs/docs/configure-ci-cd-pipeline/triggers/cron-triggers/).

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] expression: The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        :param pulumi.Input[str] message: The message which will be passed to the pipeline upon each trigger.
        :param pulumi.Input[str] pipeline_id: The pipeline to which this trigger belongs.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PipelineCronTriggerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## # Pipeline Cron Trigger resource

        Pipeline Cron Trigger is used to create cron-based triggers for pipeilnes.
        See the [documentation](https://codefresh.io/docs/docs/configure-ci-cd-pipeline/triggers/cron-triggers/).

        :param str resource_name: The name of the resource.
        :param PipelineCronTriggerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PipelineCronTriggerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expression: Optional[pulumi.Input[str]] = None,
                 message: Optional[pulumi.Input[str]] = None,
                 pipeline_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PipelineCronTriggerArgs.__new__(PipelineCronTriggerArgs)

            if expression is None and not opts.urn:
                raise TypeError("Missing required property 'expression'")
            __props__.__dict__["expression"] = expression
            if message is None and not opts.urn:
                raise TypeError("Missing required property 'message'")
            __props__.__dict__["message"] = message
            if pipeline_id is None and not opts.urn:
                raise TypeError("Missing required property 'pipeline_id'")
            __props__.__dict__["pipeline_id"] = pipeline_id
        super(PipelineCronTrigger, __self__).__init__(
            'codefresh:index/pipelineCronTrigger:PipelineCronTrigger',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            expression: Optional[pulumi.Input[str]] = None,
            message: Optional[pulumi.Input[str]] = None,
            pipeline_id: Optional[pulumi.Input[str]] = None) -> 'PipelineCronTrigger':
        """
        Get an existing PipelineCronTrigger resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] expression: The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        :param pulumi.Input[str] message: The message which will be passed to the pipeline upon each trigger.
        :param pulumi.Input[str] pipeline_id: The pipeline to which this trigger belongs.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PipelineCronTriggerState.__new__(_PipelineCronTriggerState)

        __props__.__dict__["expression"] = expression
        __props__.__dict__["message"] = message
        __props__.__dict__["pipeline_id"] = pipeline_id
        return PipelineCronTrigger(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def expression(self) -> pulumi.Output[str]:
        """
        The cron expression. Visit [this page](https://github.com/codefresh-io/cronus/blob/master/docs/expression.md) to learn about the supported cron expression format and aliases.
        """
        return pulumi.get(self, "expression")

    @property
    @pulumi.getter
    def message(self) -> pulumi.Output[str]:
        """
        The message which will be passed to the pipeline upon each trigger.
        """
        return pulumi.get(self, "message")

    @property
    @pulumi.getter(name="pipelineId")
    def pipeline_id(self) -> pulumi.Output[str]:
        """
        The pipeline to which this trigger belongs.
        """
        return pulumi.get(self, "pipeline_id")

