// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Codefresh.Inputs
{

    public sealed class StepTypesVersionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// YAML String containing a valid definition of a typed plugin
        /// </summary>
        [Input("stepTypesYaml", required: true)]
        public Input<string> StepTypesYaml { get; set; } = null!;

        /// <summary>
        /// String representing the semVer for the step
        /// </summary>
        [Input("versionNumber", required: true)]
        public Input<string> VersionNumber { get; set; } = null!;

        public StepTypesVersionGetArgs()
        {
        }
        public static new StepTypesVersionGetArgs Empty => new StepTypesVersionGetArgs();
    }
}
