// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Account Admins resource
 *
 * Use this resource to set a list of admins for any account.
 *
 * ## Example Usage
 * ### Example 2
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as codefresh from "@pierskarsenbarg/codefresh";
 * import * as codefresh from "@pulumi/codefresh";
 *
 * const testAccount = new codefresh.Account("testAccount", {
 *     limits: [{
 *         collaborators: 25,
 *         dataRetentionWeeks: 5,
 *     }],
 *     builds: [{
 *         parallel: 2,
 *     }],
 * });
 * const admin = codefresh.getUser({
 *     email: "<EXISTING USER EMAIL>",
 * });
 * const testAccountAdmins = new codefresh.AccountAdmins("testAccountAdmins", {
 *     accountId: testAccount.id,
 *     users: [admin.then(admin => admin.userId)],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import codefresh:index/accountAdmins:AccountAdmins test xxxxxxxxxxxxxxxxxxx
 * ```
 */
export class AccountAdmins extends pulumi.CustomResource {
    /**
     * Get an existing AccountAdmins resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountAdminsState, opts?: pulumi.CustomResourceOptions): AccountAdmins {
        return new AccountAdmins(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'codefresh:index/accountAdmins:AccountAdmins';

    /**
     * Returns true if the given object is an instance of AccountAdmins.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountAdmins {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountAdmins.__pulumiType;
    }

    /**
     * The account id where to set up a list of admins.
     */
    public readonly accountId!: pulumi.Output<string>;
    /**
     * A list of users to set up as account admins.
     */
    public readonly users!: pulumi.Output<string[]>;

    /**
     * Create a AccountAdmins resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountAdminsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountAdminsArgs | AccountAdminsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountAdminsState | undefined;
            resourceInputs["accountId"] = state ? state.accountId : undefined;
            resourceInputs["users"] = state ? state.users : undefined;
        } else {
            const args = argsOrState as AccountAdminsArgs | undefined;
            if ((!args || args.accountId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if ((!args || args.users === undefined) && !opts.urn) {
                throw new Error("Missing required property 'users'");
            }
            resourceInputs["accountId"] = args ? args.accountId : undefined;
            resourceInputs["users"] = args ? args.users : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccountAdmins.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountAdmins resources.
 */
export interface AccountAdminsState {
    /**
     * The account id where to set up a list of admins.
     */
    accountId?: pulumi.Input<string>;
    /**
     * A list of users to set up as account admins.
     */
    users?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a AccountAdmins resource.
 */
export interface AccountAdminsArgs {
    /**
     * The account id where to set up a list of admins.
     */
    accountId: pulumi.Input<string>;
    /**
     * A list of users to set up as account admins.
     */
    users: pulumi.Input<pulumi.Input<string>[]>;
}
