// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * ## # currentAccount data module
 *
 * Return current account (owner of the token) and its users
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as codefresh from "@pulumi/codefresh";
 *
 * const acc = codefresh.getCurrentAccount({});
 * export const currentAc = acc;
 * ```
 *
 * The output example:
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * ```
 */
export function getCurrentAccount(args?: GetCurrentAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetCurrentAccountResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("codefresh:index/getCurrentAccount:getCurrentAccount", {
        "_id": args._id,
        "name": args.name,
        "users": args.users,
    }, opts);
}

/**
 * A collection of arguments for invoking getCurrentAccount.
 */
export interface GetCurrentAccountArgs {
    _id?: string;
    name?: string;
    users?: inputs.GetCurrentAccountUser[];
}

/**
 * A collection of values returned by getCurrentAccount.
 */
export interface GetCurrentAccountResult {
    readonly _id?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name?: string;
    readonly users?: outputs.GetCurrentAccountUser[];
}

export function getCurrentAccountOutput(args?: GetCurrentAccountOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCurrentAccountResult> {
    return pulumi.output(args).apply(a => getCurrentAccount(a, opts))
}

/**
 * A collection of arguments for invoking getCurrentAccount.
 */
export interface GetCurrentAccountOutputArgs {
    _id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    users?: pulumi.Input<pulumi.Input<inputs.GetCurrentAccountUserArgs>[]>;
}
